language: php
php:
    - 5.5
before_script:
    - mysql -e 'create database endofcodes_test;'
    - cd database/migration
    - for i in `find .|sort|grep -v ^.$|grep -v migrate.php`; do ENVIRONMENT=test DB_NAME=travis DB_PASSWORD='' php $i; done
    - cd ../..
script: make all

